import type { TMenuItem } from "./model";

export const ITEMS: TMenuItem[] = [
  {
    id: 1,
    group: 1,
    text: "View profile",
    icon: "users/user",
    hotkey: "⌘K->P",
  },
  {
    id: 2,
    group: 1,
    text: "Settings",
    icon: "common/settings-01",
    hotkey: "⌘S",
  },
  {
    id: 3,
    group: 1,
    text: "Keyboard shortcuts",
    icon: "common/zap",
    hotkey: "?",
  },
  {
    id: 4,
    group: 2,
    text: "Company profile",
    icon: "common/home-line",
    hotkey: "⌘K->C",
  },
  { id: 5, group: 2, text: "Team", icon: "users/users-01", hotkey: "⌘K->T" },
  {
    id: 6,
    group: 2,
    text: "Invite colleagues",
    icon: "users/user-plus-01",
    hotkey: "⌘I",
  },
  {
    id: 7,
    group: 3,
    text: "Changelog",
    icon: "common/layers-two",
    hotkey: "⌘K->C",
  },
  {
    id: 8,
    group: 3,
    text: "Slack Community",
    icon: "communication/message-smile-circle",
    hotkey: "⌘K->S",
  },
  {
    id: 9,
    group: 3,
    text: "Support",
    icon: "common/help-circle",
    hotkey: "⌘/",
  },
  {
    id: 10,
    group: 3,
    text: "API",
    icon: "development/container",
    hotkey: "⌘A",
  },
  {
    id: 11,
    group: null,
    hotkey: "⌥⇧Q",
    text: "Logout",
    icon: "common/log-out",
  },
];
